//
//  StitchAICurrentVersions.swift
//  Stitch
//
//  Created by Elliot Boschwitz on 6/1/25.
//

typealias CurrentStep = Step_V0
typealias CurrentStepType = StepType_V0
typealias CurrentStitchAIPortValue = StitchAIPortValue_V0
typealias CurrentStitchAIPosition = StitchAIPosition_V0
typealias CurrentStitchAIUUID = StitchAIUUID_V0
typealias CurrentStitchAIColor = StitchAIColor_V0
typealias CurrentStitchAISize = StitchAISize_V0
typealias CurrentStitchAISizeDimension = StitchAISizeDimension_V0
typealias CurrentJavaScriptNodeSettingsAI = JavaScriptNodeSettingsAI_V0
typealias CurrentJavaScriptPortDefinitionAI = JavaScriptPortDefinitionAI_V0
typealias CurrentAIGraphCreationRequestBody = AIGraphCreationRequestBody_V0
typealias CurrentAIGraphDescriptionRequestBody = AIGraphDescriptionRequestBody_V0
typealias CurrentAIEditJsSystemPrompt = AIEditJsNodeSystemPrompt_V0
typealias CurrentAIGraphCreationResponseFormat = AIGraphCreationResponseFormat_V0
typealias CurrentAIEditJsNodeResponseFormat = AIEditJsNodeResponseFormat_V0
typealias CurrentAIEditJsNodeRequestBody = AIEditJsNodeRequestBody_V0
typealias CurrentStitchAIRequestBodyFormattable = StitchAIRequestBodyFormattable_V0
typealias CurrentAIGraphCreationContentJSON = AIGraphCreationContentJSON_V0
typealias CurrentStepActionAddNode = StepActionAddNode_V0
typealias CurrentStepActionConnectionAdded = StepActionConnectionAdded_V0
typealias CurrentStepActionChangeValueType = StepActionChangeValueType_V0
typealias CurrentStepActionSetInput = StepActionSetInput_V0
typealias CurrentStepActionLayerGroupCreated = StepActionLayerGroupCreated_V0

typealias Step = CurrentStep.Step
typealias Steps = [Step]
typealias LLMStepAction = Step
typealias LLMStepActions = [LLMStepAction]
typealias StepType = CurrentStepType.StepType
typealias StitchAIPortValue = CurrentStitchAIPortValue.StitchAIPortValue
typealias StitchAIPosition = CurrentStitchAIPosition.StitchAIPosition
typealias StitchAINodeType = CurrentStitchAIPortValue.NodeType
typealias StitchAIUUID = CurrentStitchAIUUID.StitchAIUUID
typealias StitchAIColor = CurrentStitchAIColor.StitchAIColor
typealias StitchAISize = CurrentStitchAISize.StitchAISize
typealias StitchAISizeDimension = CurrentStitchAISizeDimension.StitchAISizeDimension
typealias JavaScriptNodeSettingsAI = CurrentJavaScriptNodeSettingsAI.JavaScriptNodeSettingsAI
typealias JavaScriptPortDefinitionAI = CurrentJavaScriptPortDefinitionAI.JavaScriptPortDefinitionAI
typealias PatchAI = CurrentStep.Patch
typealias LayerAI = CurrentStep.Layer
typealias PatchOrLayerAI = CurrentStep.PatchOrLayer
typealias AIGraphCreationRequestBody = CurrentAIGraphCreationRequestBody.AIGraphCreationRequestBody
typealias AIGraphDescriptionRequestBody = CurrentAIGraphDescriptionRequestBody.AIGraphDescriptionRequestBody
typealias AIGraphCreationStepSchema = CurrentAIGraphCreationResponseFormat.AIGraphCreationStepSchema
typealias AIGraphCreationContentJSON = CurrentAIGraphCreationContentJSON.AIGraphCreationContentJSON
typealias AIEditJsNodeRequestBody = CurrentAIEditJsNodeRequestBody.AIEditJsNodeRequestBody
typealias StitchAIRequestBodyFormattable = CurrentStitchAIRequestBodyFormattable.StitchAIRequestBodyFormattable
typealias StepActionAddNode = CurrentStepActionAddNode.StepActionAddNode
typealias StepActionConnectionAdded = CurrentStepActionConnectionAdded.StepActionConnectionAdded
typealias StepActionChangeValueType = CurrentStepActionChangeValueType.StepActionChangeValueType
typealias StepActionSetInput = CurrentStepActionSetInput.StepActionSetInput
typealias StepActionLayerGroupCreated = CurrentStepActionLayerGroupCreated.StepActionLayerGroupCreated
