//
//  StitchAICurrentVersions.swift
//  Stitch
//
//  Created by Elliot Boschwitz on 6/1/25.
//

typealias CurrentStep = Step_V1
typealias CurrentStepType = StepType_V1
typealias CurrentStitchAIPortValue = StitchAIPortValue_V1
typealias CurrentStitchAIPosition = StitchAIPosition_V1
typealias CurrentStitchAIUUID = StitchAIUUID_V1
typealias CurrentStitchAIColor = StitchAIColor_V1
typealias CurrentStitchAISize = StitchAISize_V1
typealias CurrentStitchAISizeDimension = StitchAISizeDimension_V1
typealias CurrentJavaScriptNodeSettingsAI = JavaScriptNodeSettingsAI_V1
typealias CurrentJavaScriptPortDefinitionAI = JavaScriptPortDefinitionAI_V1
typealias CurrentAIGraphCreationRequestBody = AIGraphCreationRequestBody_V1
typealias CurrentAIGraphDescriptionRequestBody = AIGraphDescriptionRequestBody_V1
typealias CurrentAIEditJsSystemPrompt = AIEditJsNodeSystemPrompt_V1
typealias CurrentAIGraphCreationResponseFormat = AIGraphCreationResponseFormat_V1
typealias CurrentAIEditJsNodeResponseFormat = AIEditJsNodeResponseFormat_V1
typealias CurrentAIEditJsNodeRequestBody = AIEditJsNodeRequestBody_V1
typealias CurrentStitchAIRequestBodyFormattable = StitchAIRequestBodyFormattable_V1
typealias CurrentAIGraphCreationContentJSON = AIGraphCreationContentJSON_V1
typealias CurrentStepActionAddNode = StepActionAddNode_V1
typealias CurrentStepActionConnectionAdded = StepActionConnectionAdded_V1
typealias CurrentStepActionChangeValueType = StepActionChangeValueType_V1
typealias CurrentStepActionSetInput = StepActionSetInput_V1
typealias CurrentStepActionLayerGroupCreated = StepActionLayerGroupCreated_V1

typealias Step = CurrentStep.Step
typealias Steps = [Step]
typealias LLMStepAction = Step
typealias LLMStepActions = [LLMStepAction]
typealias StepType = CurrentStepType.StepType
typealias StitchAIPortValue = CurrentStitchAIPortValue.StitchAIPortValue
typealias StitchAIPosition = CurrentStitchAIPosition.StitchAIPosition
typealias StitchAINodeType = CurrentStitchAIPortValue.NodeType
typealias StitchAIUUID = CurrentStitchAIUUID.StitchAIUUID
typealias StitchAIColor = CurrentStitchAIColor.StitchAIColor
typealias StitchAISize = CurrentStitchAISize.StitchAISize
typealias StitchAISizeDimension = CurrentStitchAISizeDimension.StitchAISizeDimension
typealias JavaScriptNodeSettingsAI = CurrentJavaScriptNodeSettingsAI.JavaScriptNodeSettingsAI
typealias JavaScriptPortDefinitionAI = CurrentJavaScriptPortDefinitionAI.JavaScriptPortDefinitionAI
typealias PatchAI = CurrentStep.Patch
typealias LayerAI = CurrentStep.Layer
typealias PatchOrLayerAI = CurrentStep.PatchOrLayer
typealias AIGraphCreationRequestBody = CurrentAIGraphCreationRequestBody.AIGraphCreationRequestBody
typealias AIGraphDescriptionRequestBody = CurrentAIGraphDescriptionRequestBody.AIGraphDescriptionRequestBody
typealias AIGraphCreationStepSchema = CurrentAIGraphCreationResponseFormat.AIGraphCreationStepSchema
typealias AIGraphCreationContentJSON = CurrentAIGraphCreationContentJSON.AIGraphCreationContentJSON
typealias AIEditJsNodeRequestBody = CurrentAIEditJsNodeRequestBody.AIEditJsNodeRequestBody
typealias StitchAIRequestBodyFormattable = CurrentStitchAIRequestBodyFormattable.StitchAIRequestBodyFormattable
typealias StepActionAddNode = CurrentStepActionAddNode.StepActionAddNode
typealias StepActionConnectionAdded = CurrentStepActionConnectionAdded.StepActionConnectionAdded
typealias StepActionChangeValueType = CurrentStepActionChangeValueType.StepActionChangeValueType
typealias StepActionSetInput = CurrentStepActionSetInput.StepActionSetInput
typealias StepActionLayerGroupCreated = CurrentStepActionLayerGroupCreated.StepActionLayerGroupCreated
