//
//  LayerNodeEntityUtils.swift
//  Stitch
//
//  Created by Elliot Boschwitz on 6/12/24.
//

import Foundation
import StitchSchemaKit

extension LayerNodeEntity {
    init(nodeId: NodeId,
         layer: Layer,
         positionPort: NodeConnectionType = .values([]),
         sizePort: NodeConnectionType = .values([]),
         scalePort: NodeConnectionType = .values([]),
         anchoringPort: NodeConnectionType = .values([]),
         opacityPort: NodeConnectionType = .values([]),
         zIndexPort: NodeConnectionType = .values([]),
         masksPort: NodeConnectionType = .values([]),
         colorPort: NodeConnectionType = .values([]),
         rotationXPort: NodeConnectionType = .values([]),
         rotationYPort: NodeConnectionType = .values([]),
         rotationZPort: NodeConnectionType = .values([]),
         lineColorPort: NodeConnectionType = .values([]),
         lineWidthPort: NodeConnectionType = .values([]),
         blurPort: NodeConnectionType = .values([]),
         blendModePort: NodeConnectionType = .values([]),
         brightnessPort: NodeConnectionType = .values([]),
         colorInvertPort: NodeConnectionType = .values([]),
         contrastPort: NodeConnectionType = .values([]),
         hueRotationPort: NodeConnectionType = .values([]),
         saturationPort: NodeConnectionType = .values([]),
         pivotPort: NodeConnectionType = .values([]),
         enabledPort: NodeConnectionType = .values([]),
         blurRadiusPort: NodeConnectionType = .values([]),
         backgroundColorPort: NodeConnectionType = .values([]),
         isClippedPort: NodeConnectionType = .values([]),
         orientationPort: NodeConnectionType = .values([]),
         paddingPort: NodeConnectionType = .values([]),
         setupModePort: NodeConnectionType = .values([]),
         allAnchorsPort: NodeConnectionType = .values([]),
         cameraDirectionPort: NodeConnectionType = .values([]),
         isCameraEnabledPort: NodeConnectionType = .values([]),
         isShadowsEnabledPort: NodeConnectionType = .values([]),
         shapePort: NodeConnectionType = .values([]),
         strokePositionPort: NodeConnectionType = .values([]),
         strokeWidthPort: NodeConnectionType = .values([]),
         strokeColorPort: NodeConnectionType = .values([]),
         strokeStartPort: NodeConnectionType = .values([]),
         strokeEndPort: NodeConnectionType = .values([]),
         strokeLineCapPort: NodeConnectionType = .values([]),
         strokeLineJoinPort: NodeConnectionType = .values([]),
         coordinateSystemPort: NodeConnectionType = .values([]),
         cornerRadiusPort: NodeConnectionType = .values([]),
         canvasLineColorPort: NodeConnectionType = .values([]),
         canvasLineWidthPort: NodeConnectionType = .values([]),
         canvasPositionPort: NodeConnectionType = .values([]),
         textPort: NodeConnectionType = .values([]),
         fontSizePort: NodeConnectionType = .values([]),
         textAlignmentPort: NodeConnectionType = .values([]),
         verticalAlignmentPort: NodeConnectionType = .values([]),
         textDecorationPort: NodeConnectionType = .values([]),
         textFontPort: NodeConnectionType = .values([]),
         imagePort: NodeConnectionType = .values([]),
         videoPort: NodeConnectionType = .values([]),
         fitStylePort: NodeConnectionType = .values([]),
         clippedPort: NodeConnectionType = .values([]),
         isAnimatingPort: NodeConnectionType = .values([]),
         progressIndicatorStylePort: NodeConnectionType = .values([]),
         progressPort: NodeConnectionType = .values([]),
         model3DPort: NodeConnectionType = .values([]),
         mapTypePort: NodeConnectionType = .values([]),
         mapLatLongPort: NodeConnectionType = .values([]),
         mapSpanPort: NodeConnectionType = .values([]),
         isSwitchToggledPort: NodeConnectionType = .values([]),
         placeholderTextPort: NodeConnectionType = .values([]),
         startColorPort: NodeConnectionType = .values([]),
         endColorPort: NodeConnectionType = .values([]),
         startAnchorPort: NodeConnectionType = .values([]),
         endAnchorPort: NodeConnectionType = .values([]),
         centerAnchorPort: NodeConnectionType = .values([]),
         startAnglePort: NodeConnectionType = .values([]),
         endAnglePort: NodeConnectionType = .values([]),
         startRadiusPort: NodeConnectionType = .values([]),
         endRadiusPort: NodeConnectionType = .values([]),
         shadowColorPort: NodeConnectionType = .values([]),
         shadowOpacityPort: NodeConnectionType = .values([]),
         shadowRadiusPort: NodeConnectionType = .values([]),
         shadowOffsetPort: NodeConnectionType = .values([]),
         sfSymbolPort: NodeConnectionType = .values([]),
         videoURLPort: NodeConnectionType = .values([]),
         volumePort: NodeConnectionType = .values([]),
         spacingBetweenGridColumnsPort: NodeConnectionType = .values([]),
         spacingBetweenGridRowsPort: NodeConnectionType = .values([]),
         itemAlignmentWithinGridCellPort: NodeConnectionType = .values([]),
         hasSidebarVisibility: Bool,
         layerGroupId: NodeId?,
         isExpandedInSidebar: Bool?) {
        self.init(
            id: nodeId,
            layer: layer,
        
        // Required
            positionPort: positionPort,
            sizePort: sizePort,
            scalePort: scalePort,
            anchoringPort: anchoringPort,
            opacityPort: opacityPort,
            zIndexPort: zIndexPort,
        
        // Common
            masksPort: masksPort,
            colorPort: colorPort,
            rotationXPort: rotationXPort,
            rotationYPort: rotationYPort,
            rotationZPort: rotationZPort,
            lineColorPort: lineColorPort,
            lineWidthPort: lineWidthPort,
            blurPort: blurPort,
            blendModePort: blendModePort,
            brightnessPort: brightnessPort,
            colorInvertPort: colorInvertPort,
            contrastPort: contrastPort,
            hueRotationPort: hueRotationPort,
            saturationPort: saturationPort,
            pivotPort: pivotPort,
            enabledPort: enabledPort,
            blurRadiusPort: blurRadiusPort,
            backgroundColorPort: backgroundColorPort,
            isClippedPort: isClippedPort,
            orientationPort: orientationPort,
            paddingPort: paddingPort,
            setupModePort: setupModePort,
            allAnchorsPort: allAnchorsPort,
            cameraDirectionPort: cameraDirectionPort,
            isCameraEnabledPort: isCameraEnabledPort,
            isShadowsEnabledPort: isShadowsEnabledPort,
            shapePort: shapePort,
            strokePositionPort: strokePositionPort,
            strokeWidthPort: strokeWidthPort,
            strokeColorPort: strokeColorPort,
            strokeStartPort: strokeStartPort,
            strokeEndPort: strokeEndPort,
            strokeLineCapPort: strokeLineCapPort,
            strokeLineJoinPort: strokeLineJoinPort,
            coordinateSystemPort: coordinateSystemPort,
            cornerRadiusPort: cornerRadiusPort,
            canvasLineColorPort: canvasLineColorPort,
            canvasLineWidthPort: canvasLineWidthPort,
            canvasPositionPort: canvasPositionPort,
            textPort: textPort,
            fontSizePort: fontSizePort,
            textAlignmentPort: textAlignmentPort,
            verticalAlignmentPort: verticalAlignmentPort,
            textDecorationPort: textDecorationPort,
            textFontPort: textFontPort,
            imagePort: imagePort,
            videoPort: videoPort,
            fitStylePort: fitStylePort,
            clippedPort: clippedPort,
            isAnimatingPort: isAnimatingPort,
            progressIndicatorStylePort: progressIndicatorStylePort,
            progressPort: progressPort,
            model3DPort: model3DPort,
            mapTypePort: mapTypePort,
            mapLatLongPort: mapLatLongPort,
            mapSpanPort: mapSpanPort,
            isSwitchToggledPort: isSwitchToggledPort,
            placeholderTextPort: placeholderTextPort,
            startColorPort: startColorPort,
            endColorPort: endColorPort,
            startAnchorPort: startAnchorPort,
            endAnchorPort: endAnchorPort,
            centerAnchorPort: centerAnchorPort,
            startAnglePort: startAnglePort,
            endAnglePort: endAnglePort,
            startRadiusPort: startRadiusPort,
            endRadiusPort: endRadiusPort,
            
            shadowColorPort: shadowColorPort,
            shadowOpacityPort: shadowOpacityPort,
            shadowRadiusPort: shadowRadiusPort,
            shadowOffsetPort: shadowOffsetPort,
            
            sfSymbolPort: sfSymbolPort,
            
            videoURLPort: videoURLPort,
            volumePort: volumePort,
            
            spacingBetweenGridColumnsPort: spacingBetweenGridColumnsPort,
            spacingBetweenGridRowsPort: spacingBetweenGridRowsPort,
            itemAlignmentWithinGridCellPort: itemAlignmentWithinGridCellPort,
            
            hasSidebarVisibility: hasSidebarVisibility,
            layerGroupId: layerGroupId,
            isExpandedInSidebar: isExpandedInSidebar)
    }
}
