//
//  LayerNodeEntityUtils.swift
//  Stitch
//
//  Created by Elliot Boschwitz on 6/12/24.
//

import Foundation
import StitchSchemaKit

extension LayerInputDataEntity {
    static let empty: Self = .init(inputPort: .values([]),
                                   canvasItem: nil)
}

extension LayerNodeEntity {
    // TODO: can we move this initialzier to StitchSchemaKit ?
    init(nodeId: NodeId,
         layer: Layer,
         positionPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         sizePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         scalePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         anchoringPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         opacityPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         zIndexPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         masksPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         colorPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         rotationXPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         rotationYPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         rotationZPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         lineColorPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         lineWidthPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         blurPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         blendModePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         brightnessPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         colorInvertPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         contrastPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         hueRotationPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         saturationPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         pivotPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         enabledPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         blurRadiusPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         backgroundColorPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         isClippedPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         orientationPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         paddingPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         setupModePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         allAnchorsPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         cameraDirectionPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         isCameraEnabledPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         isShadowsEnabledPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         shapePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         strokePositionPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         strokeWidthPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         strokeColorPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         strokeStartPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         strokeEndPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         strokeLineCapPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         strokeLineJoinPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         coordinateSystemPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         cornerRadiusPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         canvasLineColorPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         canvasLineWidthPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         canvasPositionPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         textPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         fontSizePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         textAlignmentPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         verticalAlignmentPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         textDecorationPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         textFontPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         imagePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         videoPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         fitStylePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         clippedPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         isAnimatingPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         progressIndicatorStylePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         progressPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         model3DPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         mapTypePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         mapLatLongPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         mapSpanPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         isSwitchToggledPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         placeholderTextPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         startColorPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         endColorPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         startAnchorPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         endAnchorPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         centerAnchorPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         startAnglePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         endAnglePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         startRadiusPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         endRadiusPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         shadowColorPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         shadowOpacityPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         shadowRadiusPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         shadowOffsetPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         sfSymbolPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         videoURLPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         volumePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         spacingBetweenGridColumnsPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         spacingBetweenGridRowsPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         itemAlignmentWithinGridCellPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         sizingScenarioPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         widthAxisPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         heightAxisPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         contentModePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         minSizePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         maxSizePort: LayerInputDataEntity = LayerInputDataEntity.empty,
         spacingPort: LayerInputDataEntity = LayerInputDataEntity.empty,
         hasSidebarVisibility: Bool,
         layerGroupId: NodeId?,
         isExpandedInSidebar: Bool?) {
        
        let outputsCount = layer.layerGraphNode.rowDefinitions(for: nil).outputs.count
        
        self.init(
            id: nodeId,
            layer: layer,
            outputCanvasPorts: (0..<outputsCount).map { _ in nil }, // just needs to match outputs count
        
        // Required
            positionPort: positionPort,
            sizePort: sizePort,
            scalePort: scalePort,
            anchoringPort: anchoringPort,
            opacityPort: opacityPort,
            zIndexPort: zIndexPort,
        
        // Common
            masksPort: masksPort,
            colorPort: colorPort,
            rotationXPort: rotationXPort,
            rotationYPort: rotationYPort,
            rotationZPort: rotationZPort,
            lineColorPort: lineColorPort,
            lineWidthPort: lineWidthPort,
            blurPort: blurPort,
            blendModePort: blendModePort,
            brightnessPort: brightnessPort,
            colorInvertPort: colorInvertPort,
            contrastPort: contrastPort,
            hueRotationPort: hueRotationPort,
            saturationPort: saturationPort,
            pivotPort: pivotPort,
            enabledPort: enabledPort,
            blurRadiusPort: blurRadiusPort,
            backgroundColorPort: backgroundColorPort,
            isClippedPort: isClippedPort,
            orientationPort: orientationPort,
            paddingPort: paddingPort,
            setupModePort: setupModePort,
            allAnchorsPort: allAnchorsPort,
            cameraDirectionPort: cameraDirectionPort,
            isCameraEnabledPort: isCameraEnabledPort,
            isShadowsEnabledPort: isShadowsEnabledPort,
            shapePort: shapePort,
            strokePositionPort: strokePositionPort,
            strokeWidthPort: strokeWidthPort,
            strokeColorPort: strokeColorPort,
            strokeStartPort: strokeStartPort,
            strokeEndPort: strokeEndPort,
            strokeLineCapPort: strokeLineCapPort,
            strokeLineJoinPort: strokeLineJoinPort,
            coordinateSystemPort: coordinateSystemPort,
            cornerRadiusPort: cornerRadiusPort,
            canvasLineColorPort: canvasLineColorPort,
            canvasLineWidthPort: canvasLineWidthPort,
            canvasPositionPort: canvasPositionPort,
            textPort: textPort,
            fontSizePort: fontSizePort,
            textAlignmentPort: textAlignmentPort,
            verticalAlignmentPort: verticalAlignmentPort,
            textDecorationPort: textDecorationPort,
            textFontPort: textFontPort,
            imagePort: imagePort,
            videoPort: videoPort,
            fitStylePort: fitStylePort,
            clippedPort: clippedPort,
            isAnimatingPort: isAnimatingPort,
            progressIndicatorStylePort: progressIndicatorStylePort,
            progressPort: progressPort,
            model3DPort: model3DPort,
            mapTypePort: mapTypePort,
            mapLatLongPort: mapLatLongPort,
            mapSpanPort: mapSpanPort,
            isSwitchToggledPort: isSwitchToggledPort,
            placeholderTextPort: placeholderTextPort,
            startColorPort: startColorPort,
            endColorPort: endColorPort,
            startAnchorPort: startAnchorPort,
            endAnchorPort: endAnchorPort,
            centerAnchorPort: centerAnchorPort,
            startAnglePort: startAnglePort,
            endAnglePort: endAnglePort,
            startRadiusPort: startRadiusPort,
            endRadiusPort: endRadiusPort,
            
            shadowColorPort: shadowColorPort,
            shadowOpacityPort: shadowOpacityPort,
            shadowRadiusPort: shadowRadiusPort,
            shadowOffsetPort: shadowOffsetPort,
            
            sfSymbolPort: sfSymbolPort,
            
            videoURLPort: videoURLPort,
            volumePort: volumePort,
            
            spacingBetweenGridColumnsPort: spacingBetweenGridColumnsPort,
            spacingBetweenGridRowsPort: spacingBetweenGridRowsPort,
            itemAlignmentWithinGridCellPort: itemAlignmentWithinGridCellPort,
            
            sizingScenarioPort: sizingScenarioPort,
            
            widthAxisPort: widthAxisPort,
            heightAxisPort: heightAxisPort,
            contentModePort: contentModePort,
            minSizePort: minSizePort,
            maxSizePort: maxSizePort,
            spacingPort: spacingPort,
            
            hasSidebarVisibility: hasSidebarVisibility,
            layerGroupId: layerGroupId,
            isExpandedInSidebar: isExpandedInSidebar)
    }
}
